### PR TITLE
chore: add quickstart template

### PR DESCRIPTION
**Pull request by marcellmueller**
## WIP 

Setting up project using https://github.com/bcgov/quickstart-openshift modified to comment/remove OpenShift specific features.

## Todo:

- [x] Request Renovate setup
- [x] Request SonarCloud tokens
     - [ ] Add SonarCloud tokens to secrets
- [x] Delete charts directory
- [x] Comment deployment workflows and remove OpenShift specific jobs and secrets
- [x] Update `Readme.md`

### Todo after merge to main:
- [ ] Setup SchemaSpy `gh-pages`
- [ ] Add Trivy to branch Ruleset code scanning results
- [ ] Add required status checks:
     - [ ] Analysis Results
     - [ ] PR Results
     - [ ] Validate Results

### Notes:
- Replaced jest with Vitest in the `/backend` project 🎉 
- Added pre-commit hooks
- Added bcparks.ca bootstrap theme. The BCGov React component library seems awesome so leaving it in the project for now, though I think we will have to mostly use the bootstrap theme for consistency since we are aligning with Parks.
- Removed MUI completely - absolutely nothing against MUI, though I'm not planning on using MUI box for styling so we can always add back if we decide we need a helpful library such as the DataGrid.
- For now we can use vanilla CSS modules for styling. We will likely be using the bootstrap theme which uses scss, though the Vite docs recommend PostCSS plugins if we need to extend vanilla CSS features.

#### Eslint
Configuring eslint to work on the monorepo and not just the frontend ended up being a big pain. I *think* it's mostly working correctly now 🤞 

- [ESLint 8 is EOL ](https://eslint.org/version-support/) so I [migrated to eslint 9](https://eslint.org/docs/latest/use/configure/migration-guide) which uses flat config
- Added eslint config in root of project
- Frontend extends that config with React specific plugins and rules
- Added eslint pre-commit hook
- Perhaps in the future we will want to add an eslint config to the `/backend` project. Though I think using the base config is fine for now.

### CODE REVIEW

**Comment by mishraomp** [comment]
great going @marcellmueller ,  Looking forward to steal some items, `vitest for backend`, `precommit hooks`

cc @DerekRoberts

**Comment by marcellmueller** [comment]
> great going @marcellmueller , Looking forward to steal some items, `vitest for backend`, `precommit hooks`
> 
> cc @DerekRoberts

Thanks! I still need to configure eslint for the monorepo and add eslint to pre-commit.

**Comment by DerekRoberts** [comment]
I'm not a fan of pre-commit hooks because discourage frequent committing and updating. People can circumvent with use '--no-verify' too. Just let the pipeline handle this.

Over here only the capstone project, which was all students, has suffered through Husky.  @marcellmueller @mishraomp

**Comment by mishraomp** [comment]
> I'm not a fan of precommit hooks because they impede frequent pushing and updating. People can circumvent with '--no-verify' too. Letting the CI (workflow) handle it is ideal! We have several examples.
> 
> Over here only the capstone project, which was all students, has suffered through Husky. @marcellmueller @mishraomp

well I take my words back `rip husky`

**Comment by DerekRoberts** [comment]
@mishraomp Lol!  It's not all bad, just maybe a little remedial.  :D + :P

**Comment by marcellmueller** [comment]
> I'm not a fan of precommit hooks because they impede frequent pushing and updating. People can circumvent with '--no-verify' too. Letting the CI (workflow) handle it is ideal! We have several examples.
> 
> Over here only the capstone project, which was all students, has suffered through Husky. @marcellmueller @mishraomp

Well it might be a good idea to leave it out of the OpenShift quickstart though I think pre-commit hooks are very useful. Without it the team regularly commits messy or even broken code and as someone who isn't a fan of nit-heavy PR reviews having eslint properly implemented with pre-commit helps mitigate that. 

I think the quickstart template is a good example of this, as it has numerous linting errors once eslint was fixed and formatting inconsistencies ;)

Using the `--no-verify` flag is also a valid workflow, you can always run `pre-commit run --all-files` on your PR before review so it will pass CI.

**Comment by DerekRoberts** [comment]
@marcellmueller Given that arugment, sure!  It's easier for teams to remove features than add, so we could be helping teams by annoying them.  :D  ...the linting errors point more to us needing help rather than any high-level decision making.  :/ @mishraomp

**Comment by DerekRoberts** [comment]
@marcellmueller Can you be conned into providing these improvements to the QuickStart?  We'd most definitey appreciate it.  :)  @mishraomp

**Comment by marcellmueller** [comment]
> @marcellmueller Can you be conned into providing these improvements to the QuickStart? We'd most definitey appreciate it. :) @mishraomp

I'd love to help with some PRs. I'll make sure my PO is good with me spending a little time contributing back. Would love to prioritize getting eslint working for the entire project and Vitest as the backend test runner for consistency if that is okay :)

**Review by mishraomp — APPROVED** [review]
nicely done, lgtm

**Comment by marcellmueller** [comment]
> @marcellmueller That'd be great, thanks! ...worst case we can just "liberate" your ideas using good old theft. :D + :P

Hey I tried to open a PR for replacing Jest with Vitest in the backend, however I don't have access to create a branch. Can I get access to do that?

**Comment by DerekRoberts** [comment]
> > @marcellmueller That'd be great, thanks! ...worst case we can just "liberate" your ideas using good old theft. :D + :P
> 
> Hey I tried to open a PR for replacing Jest with Vitest in the backend, however I don't have access to create a branch. Can I get access to do that?

@marcellmueller Sorry, you now have write access! Thanks, we're looking forward to this. :) @mishraomp

**Pull request merged**
