### PR TITLE
chore: fix trivy workflow permissions

### PR DESCRIPTION
**Pull request by marcellmueller**
Trivy is failing on merge to main:

```
  Warning: Resource not accessible by integration
  Error: Resource not accessible by integration
```

Edit: @DerekRoberts figured it out, it was the permissions set for commitlint at the top of the file 🙃 I've moved them to the commitlint job so it shouldn't affect Trivy anymore.

### CODE REVIEW

**Comment by marcellmueller** [comment]
@mishraomp Any thoughts on this? It's not failing in `quickstart-openshift` repo, maybe they are using PAT?

**Comment by mishraomp** [comment]
> @mishraomp Any thoughts on this? It's not failing in `quickstart-openshift` repo, maybe they are using PAT?

I dont think we ever use PAT, @DerekRoberts thoughts?

**Comment by DerekRoberts** [comment]
@marcellmueller No, we're not using PATs...  GitHub has been having a lot of trouble today.  Retry the job and see if this is still happening?

**Review by mishraomp — APPROVED** [review]
lgtm

**Pull request merged**
